const cupons = [
  {
    img: "src/img/202306-cupom-adega.jpg",
    title: "Abasteça sua adega",
    description: "20% de desconto nos melhores rótulos!",
    cupomCode: "VINHO20",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "20VINHO",
  },
  {
    img: "src/img/202306-cupom-organizadores.jpg",
    title: "Organização e praticidade no dia-a-dia",
    description: "10% de desconto em organizadores!",
    cupomCode: "ORGANIZE",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "ORGANIZE10",
  },
  {
    img: "src/img/202306-cupom-impressora.jpg",
    title: "Imprimir ficou mais fácil",
    description: "10% de desconto em impressoras e multifuncionais!",
    cupomCode: "IMPRESSAO",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "IMPRESSAO10",
  },
  {
    img: "src/img/202306-cupom-fita3m.jpg",
    title: "Cole tudo com 3M",
    description: "10% de desconto em fitas 3M!",
    cupomCode: "FITAS3M",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "FITAS10",
  },
  {
    img: "src/img/202306-cupom-mop.jpg",
    title: "Mop para todo tipo de limpeza",
    description: "15% de desconto na compra de qualquer mop!",
    cupomCode: "15MOP",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "MOP15",
  },
  {
    img: "src/img/202306-cupom-johnson.jpg",
    title: "Facilite sua limpeza com SC Johnson",
    description: "10% de desconto em qualquer produto SC Johnson!",
    cupomCode: "SCLIMPEZA",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "JOHNSON",
  },
  {
    img: "src/img/202306-cupom-headphone.jpg",
    title: "Sua música com você",
    description: "10% de desconto em headphones!",
    cupomCode: "HEADPHONE",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "HEADPHONE10",
  },
  {
    img: "src/img/202306-cupom-headphone.jpg",
    title: "Prepare bons drinks",
    description: "20% de desconto em destilados!",
    cupomCode: "DESTILADOS",
    cupomMessage: "no app utilize o cupom",
    cupomAppCode: "DESTILADOS20",
  },
];
