export const cupons = [
  {
    img_alt: "Imagem de vinhos",
    img: "src/img/202306-cupom-adega.jpg",
    title: "Abasteça sua adega",
    description: "20% de desconto nos melhores rótulos!",
    cupomCode: "VINHO20",
    cupomAppCode: "20VINHO",
    link: "https://bit.ly/3C4SrAr",
  },
  {
    img_alt: "Imagem de organizadores diversos",
    img: "src/img/202306-cupom-organizadores.jpg",
    title: "Organização e praticidade no dia-a-dia",
    description: "10% de desconto em organizadores!",
    cupomCode: "ORGANIZE",
    cupomAppCode: "ORGANIZE10",
    link: "https://bit.ly/3ISXh7P",
  },
  {
    img_alt: "Imagem de impressoras",
    img: "src/img/202306-cupom-impressora.jpg",
    title: "Imprimir ficou mais fácil",
    description: "10% de desconto em impressoras e multifuncionais!",
    cupomCode: "IMPRESSAO",
    cupomAppCode: "IMPRESSAO10",
    link: "https://bit.ly/3IQzeGD",
  },
  {
    img_alt: "Imagem de fitas diversas",
    img: "src/img/202306-cupom-fita3m.jpg",
    title: "Cole tudo com 3M",
    description: "10% de desconto em fitas 3M!",
    cupomCode: "FITAS3M",
    cupomAppCode: "FITAS10",
    link: "https://bit.ly/3oLVbzF",
  },
  {
    img_alt: "Imagem de mops de limpeza",
    img: "src/img/202306-cupom-mop.jpg",
    title: "Mop para todo tipo de limpeza",
    description: "15% de desconto na compra de qualquer mop!",
    cupomCode: "15MOP",
    cupomAppCode: "MOP15",
    link: "https://bit.ly/3IM7mna",
  },
  {
    img_alt: "Imagem de produtos de limpeza",
    img: "src/img/202306-cupom-johnson.jpg",
    title: "Facilite sua limpeza com SC Johnson",
    description: "10% de desconto em qualquer produto SC Johnson!",
    cupomCode: "SCLIMPEZA",
    cupomAppCode: "JOHNSON",
    link: "https://bit.ly/45DXzJA",
  },
  {
    img_alt: "Imagem de headphones",
    img: "src/img/202306-cupom-headphone.jpg",
    title: "Sua música com você",
    description: "10% de desconto em headphones!",
    cupomCode: "HEADPHONE",
    cupomAppCode: "HEADPHONE10",
    link: "https://bit.ly/42qFMCY",
  },
  {
    img_alt: "Imagem de bebidas alcoólicas",
    img: "src/img/202306-cupom-destilado.jpg",
    title: "Prepare bons drinks",
    description: "20% de desconto em destilados!",
    cupomCode: "DESTILADOS",
    cupomAppCode: "DESTILADOS20",
    link: "https://bit.ly/42h4fum",
  },
];
